package src.util;



public enum ScriptElement {
    NUMBER,
    NUMERIC_EXPRESSION,
    RELATIONAL_EXPRESSION,
    EXPRESSION,
    OPERAND,
    BRACKETS,
    FUNCTION,
    STATEMENT,
    INIT_VAR,
    PROGRAM,
    PROCEDURE,
    READ_VARIABLE,
    WHILE_OPERATOR,
    BOOLEAN_EXPRESSION,
    BOOLEAN_OPERAND
}
